name: estado
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  go_router: ^16.0.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^3.1.0
  json_serializable: ^6.6.1 
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true